name: cryptude
description: cryptude App


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  badges: ^2.0.2
  intl: ^0.17.0
  shared_preferences: ^2.0.13
  get: ^4.6.1
  carousel_slider: ^4.1.1
  shimmer: ^2.0.0
  http: ^0.13.4
  otp_text_field: ^1.1.3
  flutter_easyloading: ^3.0.3
  share_plus: ^4.0.6
  clipboard: ^0.1.2+8
  webview_flutter: ^3.0.4
  #image_picker: ^0.8.5+3


dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.6

flutter_native_splash:
    color: "#ffffff"
    image: images/new_logo.png
    android: true
    ios: true
#    flutter pub run flutter_native_splash:create

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  uses-material-design: true

  assets:
     - images/
  #   - images/a_dot_ham.jpeg


  #fonts:
  #   - family: Nunito-Black
  #     fonts:
  #       - asset: fonts/Nunito-Black.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
